### ISSUE TITLE
Without docker

### ISSUE THREAD

**Issue by jaikishantulswani** [Rev3rseSecurity/WebMap#3]
Can we run this without docker ?

**Comment by theMiddleBlue** [comment]
Hi @jaikishantulswani 

IMHO it isn't a good idea just because you need to install django, configure the app, create all required paths and install required deps. Then, for the PDF Report you need to install wkhtmltopdf... 

If you want to try anyway, you could checkout the django-project branch that includes all django project files (such as settings.py, etc...).
